name: tdd_clean_architecture_resocoder
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  # Get_X for state management
  get: ^3.25.6
  flutter_bloc: ^7.0.0
  # Value equality
  equatable: ^2.0.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  # Swap the connectivity package for this
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0


flutter:


  uses-material-design: true


